### ISSUE TITLE
crashes at launch on M1 MacBook

### ISSUE THREAD

**Issue by LachlanMalec** [onionshare/onionshare#1471] opened 2021-11-15 03:26 UTC
Information:
- OnionShare installed via brew using the command given in readme
- Running macOS 12.0.1 21A559 arm64
- M1 MacBook Pro 13inch with 16GB RAM and 512GB Storage

Attempted Fixes:
- Manually installing missing module with pip

Error Text:
From window titled "Application has crashed!"
```
Traceback (most recent call last):
  File "OnionShare.app/Contents/Resources/Support/Python/Resources/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "OnionShare.app/Contents/Resources/app/onionshare/__init__.py", line 27, in <module>
    import psutil
  File "OnionShare.app/Contents/Resources/app_packages/psutil/__init__.py", line 121, in <module>
    from . import _psosx as _psplatform
  File "OnionShare.app/Contents/Resources/app_packages/psutil/_psosx.py", line 15, in <module>
    from . import _psutil_osx as cext
ImportError: dlopen(/Applications/OnionShare.app/Contents/Resources/app_packages/psutil/_psutil_osx.cpython-38-darwin.so, 0x0002): tried: '/Applications/OnionShare.app/Contents/Resources/app_packages/psutil/_psutil_osx.cpython-38-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/_psutil_osx.cpython-38-darwin.so' (no such file)
```

**Comment by LachlanMalec** [comment] 2021-11-15 03:39
Workaround: Forcing OnionShare to run under Rosetta 2 (x86_64 emulation) results in normal launch and operation. 

Possible Fix: Setting this option (run under Rosetta 2) as default for future MacOS releases.

**Comment by mig5** [comment] 2021-11-15 03:42
Thanks. It's a duplicate of https://github.com/onionshare/onionshare/issues/1414

**Closed by mig5** 2021-11-15 03:42 UTC
