### ISSUE TITLE
Latest version of Tor doesn't support stealth

### ISSUE THREAD

**Issue by gianmarcogg03** [onionshare/onionshare#1469] opened 2021-11-14 17:18 UTC
I'm using OnionShare 2.4-2 on Arch Linux with Tor version 0.4.6.8-1 and I can't enable services with a private key, I get an error saying:
```
Sorry, this version of Tor doesn't support stealth (Client Authentication). Please try with a newer version of Tor, or use 'public' mode if it doesn't need to be private.
```

**Comment by Stetsed** [comment] 2021-11-14 18:37
This seems to be a problem with the arch linux version of onionshare as replacing it with the flatpak(nothing else changed) seemed to fix it.

**Comment by mig5** [comment] 2021-11-15 01:10
Seems like a duplicate of #1465

**Closed by mig5** 2021-11-15 01:10 UTC
