### ISSUE TITLE
Could not connect to Tor: socket connection failed ([Errno 2] No such file or directory)

### ISSUE THREAD

**Issue by lucy2812** [onionshare/onionshare#1373] opened 2021-06-03 18:14 UTC
I am trying to start OnionShare and receive this error message:

> OnionShare could not connect to Tor:
> socket connection failed ([Errno 2] No such file or directory)

Test connection for Tor = 100% successful.

I tried other methods to connect to Tor without success.

I don't believe I had this problem in the prior version.

I also started from the command line:

> $ flatpak run org.onionshare.OnionShare
> Gtk-Message: Failed to load module "xapp-gtk3-module"
> Gtk-Message: Failed to load module "canberra-gtk-module"
> Qt: Session management error: None of the authentication protocols specified are supported
> OnionShare could not connect to Tor:
> socket connection failed ([Errno 2] No such file or directory)
> QThread: Destroyed while thread is still running

Currently using OnionShare v2.3.2
Linux
Flatpak

**Comment by mig5** [comment] 2021-09-29 06:03
I think it's a duplicate of https://github.com/onionshare/onionshare/issues/1403

Try deleting `~/.config/onionshare` and then re-launching it. It's possible something in your settings is corrupted and preventing it from starting.

**Closed by mig5** 2021-09-29 06:03 UTC
