### ISSUE TITLE
Onion Share dont Work

### ISSUE THREAD

**Issue by mydgz** [onionshare/onionshare#1593] opened 2022-06-11 20:52 UTC
Can anyone help me to solve this problem?

![1](https://user-images.githubusercontent.com/107325091/173204482-640f72b3-267d-458e-b6f5-de5194df015f.jpg)

![1A](https://user-images.githubusercontent.com/107325091/173204484-ff54f15b-5cc7-4d17-973c-e6bdbd4a54cd.jpg)

![1B](https://user-images.githubusercontent.com/107325091/173204485-730e2574-9768-4da4-a894-715e4fe2e72b.jpg)

**Comment by mig5** [comment] 2022-06-16 04:31
This looks like a duplicate of https://github.com/onionshare/onionshare/issues/1512

It has been fixed in git and the next release of OnionShare will contain that fix (no ETA on the next release, it's coming 'soon'). Sorry for the inconvenience.

**Closed by mig5** 2022-06-16 04:31 UTC
