### ISSUE TITLE
Apple Monterey / Silicon issue?

### ISSUE THREAD

**Issue by harrisondesbrosses** [onionshare/onionshare#1457] opened 2021-11-07 04:08 UTC
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,4
  Chip:	Apple M1 Max
  Total Number of Cores:	10 (8 performance and 2 efficiency)
  Memory:	32 GB

Running 12.0.1 

Upon opening, I get a notice that the app has crashed, see below.

I would appreciate any input any one might have, thank you. I love onionshare :)

"Application has crashed!

Traceback (most recent call last):
  File "OnionShare.app/Contents/Resources/Support/Python/Resources/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "OnionShare.app/Contents/Resources/app/onionshare/__init__.py", line 27, in <module>
    import psutil
  File "OnionShare.app/Contents/Resources/app_packages/psutil/__init__.py", line 121, in <module>
    from . import _psosx as _psplatform
  File "OnionShare.app/Contents/Resources/app_packages/psutil/_psosx.py", line 15, in <module>
    from . import _psutil_osx as cext
ImportError: dlopen(/Applications/OnionShare.app/Contents/Resources/app_packages/psutil/_psutil_osx.cpython-38-darwin.so, 0x0002): tried: '/Applications/OnionShare.app/Contents/Resources/app_packages/psutil/_psutil_osx.cpython-38-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/_psutil_osx.cpython-38-darwin.so' (no such file)"

**Comment by mig5** [comment] 2021-11-07 23:01
Sounds like a duplicate of #1414

**Closed by mig5** 2021-11-07 23:01 UTC
