### ISSUE TITLE
Receiving files Error : File is not transmitted

### ISSUE THREAD

**Issue by Cottonwoodhill** [onionshare/onionshare#1774] opened 2023-10-09 15:34 UTC
Hello,

I am encountering an issue by submitting a file. When I click "Submit" a folder is created on the taget machine but it remains empty. The file is not transmitted.
Please find below the screenshot of the OnionShare message from the  sender machine. We can read "Nothing has been submitted"
![Capture](https://github.com/onionshare/onionshare/assets/37047745/f8937455-27b9-49ab-9794-e0924f3ab697)
Would you kindly support ?

Target machine has OnionShare 2.6 installed.
Tor browser 12.5.6 is used from sender.

Thanks

**Comment by mig5** [comment] 2023-10-18 02:53
Hi @Cottonwoodhill, the only way I reproduce the "Nothing submitted" option is if I don't actually select any files but press Submit. You can see in the screenshot that this is the case, under 'Browse it says 'No files selected'.

The sender has not selected a file via the Browse button, nor have they entered any text message in the 'Write a message' option. They've clicked Submit and done nothing else.

(We should probably prevent that being possible, but that looks to be the root cause either way).

**Comment by mig5** [comment] 2023-10-18 03:07
Closing as duplicate of #936 which I'll re-open.

**Closed by mig5** 2023-10-18 03:07 UTC
Labels: question, receive mode
