### ISSUE TITLE
Does not work on Mac M1

### ISSUE THREAD

**Issue by mindaslab** [onionshare/onionshare#1497] opened 2021-12-30 15:35 UTC
Hello All,

Installed Onion Share from https://onionshare.org/dist/2.4/OnionShare-2.4.dmg , on my Mac M1, and when I try to open it, I get this error:

```
Traceback (most recent call last):
  File "OnionShare.app/Contents/Resources/Support/Python/Resources/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "OnionShare.app/Contents/Resources/app/onionshare/__init__.py", line 27, in <module>
    import psutil
  File "OnionShare.app/Contents/Resources/app_packages/psutil/__init__.py", line 121, in <module>
    from . import _psosx as _psplatform
  File "OnionShare.app/Contents/Resources/app_packages/psutil/_psosx.py", line 15, in <module>
    from . import _psutil_osx as cext
ImportError: dlopen(/Applications/OnionShare.app/Contents/Resources/app_packages/psutil/_psutil_osx.cpython-38-darwin.so, 0x0002): tried: '/Applications/OnionShare.app/Contents/Resources/app_packages/psutil/_psutil_osx.cpython-38-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/_psutil_osx.cpython-38-darwin.so' (no such file)
```

The OS I use is macOS Monterey 12.1

**Comment by mig5** [comment] 2022-01-04 00:01
Duplicate of #1414

**Closed by mig5** 2022-01-04 00:01 UTC
