### ISSUE TITLE
Server disconnects after one person downloads the file(s)

### ISSUE THREAD

**Issue by bobdaroze** [onionshare/onionshare#159] opened 2014-10-15 17:47 UTC
Greetings!
I have a problem. I think the program doesn't work as it is intented.
When a person downloads the zip file on/from the server, it automatically disconnects, no matter if I ticked the "stop server automatically option" or not.
I think the feature is somehow disabled. I'm using the latest version of each program. (Browser and O.share)

**Comment by superchief** [comment] 2015-05-13 00:50
I'm having the same issue.

**Comment by Zaxscdvf** [comment] 2015-05-15 00:47
I have the same issue on Ubuntu 14.04 and Debain 7.

**Comment by micahflee** [comment] 2015-05-15 19:38
Huh, I can't reproduce in Debian 8 with onionshare or onionshare-gui. I'll keep trying in other operating systems.

**Comment by Zaxscdvf** [comment] 2015-05-15 19:42
Any Ubuntu or Debian distro that I tried so far on a VM have had this issue.

**Comment by Zaxscdvf** [comment] 2015-05-15 20:14
I solved it so for the gui you don't have the option to set '--stay-open' so once a download is finished the server automatically stops but if you run it through the terminal 'onionsshare file.zip --stay-open' the server will stay up until you stop it.

**Comment by micahflee** [comment] 2015-05-15 21:54
I thought this issue was that the `--stay-open` flag wasn't working correctly.

Expected behavior for onionshare is: it should close immediately after the first download is done unless `--stay-open` is passed, in which case it should remain open until the user presses ctrl-c.

Expected behavior for onionshare-gui is: it should close immediately after the first download is done unless the user unchecks the "Stop server automatically" box, in which case it should stay open until the user clicks "Stop Server" or closes the window.

In my testing (in a Debian 8 VM in Qubes) it all worked exactly like it was supposed to. Maybe this isn't a bug so much as not realizing that you're supposed to use `--stay-open` if you want it to not automatically close.

**Comment by Zaxscdvf** [comment] 2015-05-15 23:00
oh nvm my issue is just stupidity everything works fine gui and command line.

**Comment by micahflee** [comment] 2015-05-16 02:09
@bobdaroze @u451f Just want to make sure, is onionshare automatically closing even when you pass `--stay-open` or uncheck "Stop server automatically"?

**Closed as completed** 2015-05-18 17:28 UTC
Labels: bug
