### ISSUE TITLE
Not starting after Ubuntu 21.10 Upgrade (wayland ?)

### ISSUE THREAD

**Issue by weinbrenner** [onionshare/onionshare#1455] opened 2021-11-01 11:19 UTC
Situation:
- Onionshare is installed via Snap (2.4)
- Was working fine under Ubuntu 20.04
- Upgraded Ubuntu to 21.04 => Onionshare is not starting anymore

Ubuntu changed the default window manager in 21.10 from X11 to wayland. This seems to cause the problem.

When starting Onionshare from console I get the following:

```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Abgebrochen (Speicherabzug geschrieben)
```

**Comment by mig5** [comment] 2021-11-09 04:23
It sounds like a duplicate of #1437

There are two potential causes that give the same error above:

1) You had an earlier version of OnionShare installed, with the language set to a language that was dropped in the new version of OnionShare 2.4. If so, edit the underlying json settings file to change the language to something else (perhaps en for English).

or (more likely)

2) The AppArmor profile is causing 'denied' events. This is a known issue but we have yet to issue a fixed version for. The ticket also shows some manual fixes for the AppArmor which worked for me https://github.com/onionshare/onionshare/issues/1437#issuecomment-932668764

**Closed by mig5** 2021-11-09 04:23 UTC
