### ISSUE TITLE
onionshare-cli depends on flask, which depends on jinja2, which depends on soft_unicode module from markupsafe, which was removed as of version 2.1.0

### ISSUE THREAD

**Issue by huyndao** [onionshare/onionshare#1585] opened 2022-05-15 20:38 UTC
```shell

$ onionshare-cli

Traceback (most recent call last):
  File "/home/user/.local/bin/onionshare-cli", line 5, in <module>
    from onionshare_cli import main
  File "/home/user/.local/pipx/venvs/onionshare-cli/lib/python3.10/site-packages/onionshare_cli/__init__.py", line 30, in <module>
    from .web import Web
  File "/home/user/.local/pipx/venvs/onionshare-cli/lib/python3.10/site-packages/onionshare_cli/web/__init__.py", line 21, in <module>
    from .web import Web
  File "/home/user/.local/pipx/venvs/onionshare-cli/lib/python3.10/site-packages/onionshare_cli/web/web.py", line 28, in <module>
    import flask
  File "/home/user/.local/pipx/venvs/onionshare-cli/lib/python3.10/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
  File "/home/user/.local/pipx/venvs/onionshare-cli/lib/python3.10/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/home/user/.local/pipx/venvs/onionshare-cli/lib/python3.10/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/home/user/.local/pipx/venvs/onionshare-cli/lib/python3.10/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/home/user/.local/pipx/venvs/onionshare-cli/lib/python3.10/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/user/.local/pipx/venvs/onionshare-cli/lib/python3.10/site-packages/markupsafe/__init__.py)
```

https://github.com/aws/aws-sam-cli/issues/3661
https://github.com/Deltares/GEOLib/issues/9
https://github.com/auroq/glotter/issues/3

**Comment by mig5** [comment] 2022-05-15 23:04
Duplicate of #1571, #1537, #1536

Fixed in #1541 (but not yet released)

**Closed by mig5** 2022-05-15 23:04 UTC
