### ISSUE TITLE
Testing of desktop build fails in Rolling Release

### ISSUE THREAD

**Issue by coogor** [onionshare/onionshare#1586] opened 2022-05-20 16:10 UTC
Hi,
I noticed that the testing of the desktop-client fails in Tumbleweed (Rolling Release) fails with a timeout since some time. 
As onionshare has a lot of external dependencies, it may be related to these? Anyone else seen this issue?

[   48s] ~/rpmbuild/BUILD/onionshare-2.5
[   48s] + pushd desktop
[   48s] ~/rpmbuild/BUILD/onionshare-2.5/desktop ~/rpmbuild/BUILD/onionshare-2.5
[   48s] + ./tests/run.sh
[   50s] ============================= test session starts ==============================
[   50s] platform linux -- Python 3.8.13, pytest-7.1.1, pluggy-1.0.0 -- /usr/bin/python3.8
[   50s] cachedir: .pytest_cache
[   50s] PySide2 5.15.2 -- Qt runtime 5.15.2 -- Qt compiled 5.15.2
[   50s] rootdir: /home/abuild/rpmbuild/BUILD/onionshare-2.5/desktop
[   50s] plugins: anyio-3.5.0, qt-4.0.2, xvfb-2.0.0
[   51s] collecting ... collected 15 items
[   51s] 
[   52s] tests/test_gui_tabs.py::TestTabs::test_01_common_tests PASSED            [  6%]
[   52s] tests/test_gui_tabs.py::TestTabs::test_02_starts_with_one_new_tab PASSED [ 13%]
[   52s] tests/test_gui_tabs.py::TestTabs::test_03_new_tab_button_opens_new_tabs PASSED [ 20%]
[   52s] tests/test_gui_tabs.py::TestTabs::test_04_close_tab_button_closes_tabs PASSED [ 26%]
[   52s] tests/test_gui_tabs.py::TestTabs::test_05_closing_last_tab_opens_new_one PASSED [ 33%]
[   52s] tests/test_gui_tabs.py::TestTabs::test_06_new_tab_mode_buttons_show_correct_modes PASSED [ 40%]
[ 5455s] tests/test_gui_tabs.py::TestTabs::test_07_close_share_tab_while_server_started_should_warn qemu-kvm: terminating on signal 15 from pid 26805 (<unknown process>)

**Comment by mig5** [comment] 2022-10-09 22:42
I think it's a duplicate of #1510

**Closed by mig5** 2022-10-09 22:42 UTC
