### ISSUE TITLE
Chat functionality broken on Arch Linux in 2.5

### ISSUE THREAD

**Issue by glitsj16** [onionshare/onionshare#1531] opened 2022-02-18 14:57 UTC
Hi, I'm seeing the below errors when running onionshare on Arch Linux (fully updated). The first one seems related to the system tray code (which I do not see):

```console
$ onionshare
QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)
Connecting to the Tor network: 100% - Done
```

After clicking the 'Start Chatting' item the below errors are thrown

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/onionshare/tab/tab.py", line 371, in chat_mode_clicked
    self.chat_mode.init()
  File "/usr/lib/python3.10/site-packages/onionshare/tab/mode/chat_mode/__init__.py", line 44, in init
    self.web = Web(self.common, True, self.settings, "chat")
  File "/usr/lib/python3.10/site-packages/onionshare_cli/web/web.py", line 171, in __init__
    self.socketio.init_app(self.app)
  File "/usr/lib/python3.10/site-packages/flask_socketio/__init__.py", line 245, in init_app
    self.server = socketio.Server(**self.server_options)
  File "/usr/lib/python3.10/site-packages/socketio/server.py", line 127, in __init__
    self.eio = self._engineio_server_class()(**engineio_options)
  File "/usr/lib/python3.10/site-packages/engineio/server.py", line 145, in __init__
    raise ValueError('Invalid async_mode specified')
ValueError: Invalid async_mode specified
```

The app hangs on the command line and I need to Ctrl+C to close it down:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/onionshare/__init__.py", line 255, in shutdown
    main_window.cleanup()
  File "/usr/lib/python3.10/site-packages/onionshare/main_window.py", line 330, in cleanup
    self.tabs.cleanup()
  File "/usr/lib/python3.10/site-packages/onionshare/tab_widget.py", line 102, in cleanup
    self.tabs[tab_id].cleanup()
  File "/usr/lib/python3.10/site-packages/onionshare/tab/tab.py", line 677, in cleanup
    self.get_mode().web.cleanup()
AttributeError: 'NoneType' object has no attribute 'cleanup'
```

If I can provide additional info, please feel free to ask.

```console
$ pacman -Q onionshare python
onionshare 2.5-1
python 3.10.2-1
```

**Comment by fhodun** [comment] 2022-02-25 22:53
I experience same issue, same versions as author

**Comment by mig5** [comment] 2022-03-27 22:54
Closing as duplicate of #1510

**Closed by mig5** 2022-03-27 22:54 UTC
