### ISSUE TITLE
Chat appears to disconnect after a long period of inactivity

### ISSUE THREAD

**Issue by RaidenMK** [onionshare/onionshare#1607] opened 2022-07-25 08:07 UTC
I dont know if its a bug or not,so I post it anyway and you can check.

On the chat feature when you are in a chat and if you are inactive for awhile,the chat disconnects or you disconnect or reconnect or whatever.. And as far as I know,it shouldnt disconnect you in any way as long as the chat server is running and ofcourse when tor is running and working. So could you check it just in case? because I dont know if it should be like that or not.  (its same on onionshare 2.6-dev1 too, and probably have been like that since the chat were implemented and released)

**Comment by mig5** [comment] 2022-11-27 22:31
This actually looks like a duplicate of #1168, so I think I'll close it. Thanks for the report, it does sound like abnormal/undesired behaviour.

**Closed by mig5** 2022-11-27 22:31 UTC
Labels: chat mode
