### ISSUE TITLE
Cannot start an anonymous chat

### ISSUE THREAD

**Issue by worthl3ss** [onionshare/onionshare#1554] opened 2022-03-25 12:59 UTC
After starting a fresh session of onionshare, when I select the chat option, the following error is outputed in the terminal:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/onionshare/tab/tab.py", line 371, in chat_mode_clicked
    self.chat_mode.init()
  File "/usr/lib/python3.10/site-packages/onionshare/tab/mode/chat_mode/__init__.py", line 44, in init
    self.web = Web(self.common, True, self.settings, "chat")
  File "/usr/lib/python3.10/site-packages/onionshare_cli/web/web.py", line 171, in __init__
    self.socketio.init_app(self.app)
  File "/usr/lib/python3.10/site-packages/flask_socketio/__init__.py", line 243, in init_app
    self.server = socketio.Server(**self.server_options)
  File "/usr/lib/python3.10/site-packages/socketio/server.py", line 129, in __init__
    self.eio = self._engineio_server_class()(**engineio_options)
  File "/usr/lib/python3.10/site-packages/engineio/server.py", line 150, in __init__
    raise ValueError('Invalid async_mode specified')
ValueError: Invalid async_mode specified

```

**Comment by mig5** [comment] 2022-03-27 22:54
Closing as duplicate of #1510, #1531 (a simple search for 'Invalid async_mode specified' in the issue queue would've turned these up)

**Closed by mig5** 2022-03-27 22:54 UTC
