### ISSUE TITLE
Latest tor not supporting stealth

### ISSUE THREAD

**Issue by worthl3ss** [onionshare/onionshare#1555] opened 2022-03-25 13:01 UTC
I get the error "Sorry, this version of Tor doesn't support stealth (Client Authentication). Please try with a newer version of Tor, or use 'public' mode if it doesn't need to be private." using tor 0.4.6.9 from my package manager, it worked fine in the past

**Comment by mig5** [comment] 2022-03-27 22:55
Duplicate of #1469, #1465 .....

**Closed by mig5** 2022-03-27 22:55 UTC
