### ISSUE TITLE
Add option for automatically sharing a website

### ISSUE THREAD

**Issue by oe3gwu** [onionshare/onionshare#1813] opened 2023-11-17 15:38 UTC
OnionShare can automatically connect to the TOR Network. It also can Pin a website. But start sharing is a manual option. There should be an automatism for this too. At least on CLI level.

![grafik](https://github.com/onionshare/onionshare/assets/17622063/f0e73cdf-00d1-4049-89ba-4c74a2c52f12)

**Comment by mig5** [comment] 2023-11-19 21:22
It sounds like a duplicate of https://github.com/onionshare/onionshare/issues/1574 , in terms of the UI.

In terms of the CLI, it makes no sense/already works: executing the CLI in website mode *does* start the share automatically, there is no in-between step. You pass `--website` and the path to the folder containing your HTML files/assets.

**Closed by mig5** 2023-11-19 21:22 UTC
